Topic:
  Is it possible to automate the process of finding the best way to play a set of chords on guitar. By best, being the easiest to play while being as harmonically accurate as possible.

People already have a solution to this: 
  CAGED-method:
    about:  
      CAGED method essentially allow you to get a working position very quick given 
    limitations:
      barre chords are hard: 
        CAGED methods requires the ability to barre chords, which can be hard to execute depending on the person playing or the guitar's action. 
  Triad-method:
  Shell-Voicing:
  
  Harmonic-Complexity: 
    in a standard triad chord, the 3rd provide more identity to the Cmaj triad due to it being more 